version: '3'
services:
  web:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev3
    ports:
      - '9876:9876'
    volumes:
      - /app/node_modules
      - .:/app

  test:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev3
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
