version: '3'
services:
  web:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev3
    ports:
      - '4200:4200'
    volumes:
      - /app/node_modules
      - .:/app
